### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by brunolemos** [cuducos/twitter-cleanup#10]
If it had an UI it would be easier for people to use this

Then you could post it to product hunt and get more visibility :)

**Comment by cuducos** [comment]
Why did you close this issue, @brunolemos?

I wouldn't post to product hunt, but a web UI might make this tool more accessible to others… the problem would probably by the cost of the Botometer API usage I guess.

**Comment by cuducos** [comment]
I'm not 100% comfortable with a web version because people would have to input their API key – which might cause security concerns. What do you think about it?

**Comment by cuducos** [comment]
Closed by inactivity.
