### ISSUE TITLE
SyntaxError: invalid syntax ao iniciar

### ISSUE THREAD

**Issue by diogomoreira** [cuducos/twitter-cleanup#11]
Ao tentar iniciar a ferramenta, sou apresentado ao seguinte erro:

>  File "cleanup.py", line 91
>    yield from (User.parse(self.api, user._json) for user in users)
>             ^
> SyntaxError: invalid syntax

Vale ressaltar que ao executar `pip install -r requirements.txt` eu tive que ignorar o pacote `six`. Estou tentando rodar no MacOS High Sierra, com Python 2.7.10

**Comment by cuducos** [comment]
> com Python 2.7.10

`README.md` says it requires Python 3.6 ; )
