### ISSUE TITLE
Create a new release and publish to PyPI

### ISSUE THREAD

**Issue by b0o** [cuducos/twitter-cleanup#24]
The last PyPI release for this package was over a year ago and doesn't work for me currently (#23). A new release would be appreciated 😃

**Comment by cuducos** [comment]
Ow, true story! Thanks for the heads up. Gonna publish it tomorrow : )

**Comment by cuducos** [comment]
[Done](https://pypi.org/project/twitter-cleanup/0.0.7/) ✨
